### ISSUE TITLE
scaleway: Clean up K8s pools?

### ISSUE THREAD

**Issue by maxbrunet** [parca-dev/demo-infrastructure#7]
What is the purpose of the `pool-devl` and `pool-gp1-xs` pools? Should we remove them?

https://github.com/parca-dev/demo-infrastructure/blob/519dfc66131ded280958b2d5e21f270b2e419117/scaleway/main.tf#L59-L105

cc @metalmatze

**Comment by metalmatze** [comment]
We started with equal nodes for everything. At some point we wanted to make sure to run the Parca Pod on a bigger machine, that's when we introduced the `pool-gp1-xs`. We should check if we can get rid of this one again.
